### ISSUE TITLE
Error in SchemaLoader

### ISSUE THREAD

**Issue by eakarsu** [everit-org/json-schema#98] opened 2017-08-23 12:39 UTC
I have just run hello world for json-schema but it is failing

I have included this dependency in my project. Is is there anything I am missing?

 <dependency>
      <groupId>com.github.everit-org.json-schema</groupId>
      <artifactId>org.everit.json.schema</artifactId>
      <version>1.6.0</version>
    </dependency>

Exception in thread "main" java.lang.NoSuchMethodError: org.json.JSONObject.toMap()Ljava/util/Map;
	at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.schemaJson(SchemaLoader.java:160)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:216)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:202)
	at com.capitalone.api.sandbox.sandboxsimulatorgeneric.validation.ValidationTest.test(ValidationTest.java:23)
	at com.capitalone.api.sandbox.sandboxsimulatorgeneric.validation.ValidationTest.main(ValidationTest.java:30)

**Comment by erosb** [comment] 2017-08-23 13:40
Hello @eakarsu , how did you add the library to your project? Do you use any dependency manager like maven or gradle? If yes, then is it possible that you have an older version of org.json on the classpath which doesn't implement the JSONObject.toMap() method? Could you please post your pom.xml or build.gradle?

**Comment by eakarsu** [comment] 2017-08-23 14:25
Thanks for quick reply,
When I include 1.6.0, then maven is picking  org.json with 20140107, that I don't know why

Later, I have added org.json with version 20170516 manually to pom. Then maven picked the latest version  and deleted old org.json.

<dependencies>

		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20170516</version>
		</dependency>
		<dependency>
			<groupId>com.github.everit-org.json-schema</groupId>
			<artifactId>org.everit.json.schema</artifactId>
			<version>1.6.0</version>
		</dependency>

**Comment by erosb** [comment] 2017-08-23 14:55
Hi, maybe an other dependency in your app depended on the old version, and that one appeared on the classpath at runtime. Anyway, the problem doesn't seem to be related to this library - closing the ticket, please let me know if you face any further problems.

**Closed** 2017-08-24 11:29 UTC

**Comment by weblue** [comment] 2018-03-30 15:18
Also having this issue after cloning a previously working project; going to try cloning again. 20180130 is the org.json version, 1.8.0 json-schema, deleted all other versions of org.json from local maven repo

**Comment by erosb** [comment] 2018-03-30 15:32
There is a number of ways to investigate problems caused by conflicting versions. You can use the `mvn dependency:tree` command, but IDEs [also provide tools](https://books.sonatype.com/m2eclipse-book/reference/dependencies-sect-analyze-depend.html) for this.

Anyway, this is a maven-related problem, out of the scope of the json-schema project.

**Comment by sunray2003** [comment] 2018-03-30 16:42
I removed json-schema from my dependency, I do not see ANY org.json jar. I add json-schema to my dependency and it pulls old org.json version. This is truly a problem and not an user error.

**Comment by johnygeorge** [comment] 2018-04-06 07:28
I also have the same issue . **Java.lang.NoSuchMethodError: No virtual method toMap()Ljava/util/Map; in class Lorg/json/JSONObject;** 

I am using    "com.github.everit-org.json-schema:org.everit.json.schema:1.8.0"

```
 I/TestRunner: java.lang.NoSuchMethodError: No virtual method toMap()Ljava/util/Map; in class Lorg/json/JSONObject; or its super classes (declaration of 'org.json.JSONObject' appears in /system/framework/core-libart.jar)
        at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.schemaJson(SchemaLoader.java:175)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:250)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:236)
```
