### ISSUE TITLE
"required key not found" for simple example

### ISSUE THREAD

**Issue by afandian** [everit-org/json-schema#57] opened 2016-11-25 12:23 UTC
I cannot get the library to work with a very simple example. I am happy to create a PR but this cannot possibly be a bug?

schema:

```
{
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": ["one"],
  "properties":{
    "one": {
      "type":"string",
      "id": "http://example.com/one"
    }
  }
}
```

input:

```
{"one":"1"}
```

but I think it could just be that I'm not using the library properly?

Here is the error:
```
{
  "pointerToViolation": "#",
  "causingExceptions": [],
  "keyword": "required",
  "message": "required key [one] not found"
}
```

I've tried this on http://www.jsonschemavalidator.net/ and it appears to be valid.

**Comment by erosb** [comment] 2016-11-26 00:27
@afandian I added a reproduction testcase, but I couldn't reproduce the problem, see [here](https://github.com/everit-org/json-schema/tree/master/tests/src/test/resources/org/everit/json/schema/issues/issue57). Your input passes the validation.

Closing for this time, please clarify it, otherwise I will reopen the issue in I overlooked something.

**Closed** 2016-11-26 12:56 UTC
