### ISSUE TITLE
No causing exceptions

### ISSUE THREAD

**Issue by ivanalikin** [everit-org/json-schema#33] opened 2016-04-29 12:42 UTC
Hi,
I have an error "#: only 1 subschema matches out of 2" but it's not possible to know what exactly caused the error since the getCausingExceptions() returns an empty list.

**Comment by jebbench** [comment] 2016-05-24 11:32
I'm having the same issue; I get the message "#: 2 schema violations found" but there are no causing exceptions.

**Comment by erosb** [comment] 2016-05-24 16:39
Thanks guys for reporting it. You may send a PR with a bugfix in
CombinedSchema.java but I won't fix it on my own until the middle of June,
due to other activities.

**Comment by erosb** [comment] 2016-06-26 15:29
I've just committed the bugfix, it will be released with 1.4.0

**Closed by erosb** 2016-06-26 15:29 UTC

**Comment by Sudesh1989** [comment] 2017-06-29 14:40
Hi, iam facing the above issue when I call getCausingExceptions() method in ValidationException class. The getCausingExceptions() method returns valid exception list for multiple schema violations, but it returns empty list for a single schema violation?

**Comment by saurabhdwivedi13** [comment] 2018-10-04 16:02
I am getting this even in 1.9.2 version.

**Comment by electronABS** [comment] 2019-06-20 22:09
@erosb 
Same thing with the latest version 1.11.1 returns empty list for a single schema violation !!

**Comment by erosb** [comment] 2019-06-21 09:04
@electronABS please post reproduction details (schema, instance json).

**Comment by electronABS** [comment] 2019-06-21 10:20
@erosb 
- Schema "Report.json"

`{ 
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Report",
    "description": "A report json format",
	"type": "object",
	"required": ["startedAt" , "finishedAt" , "agentId" , "reportType" , "reportJSON"],
    "properties": {
        "agentId": {
            "description": "The agent's who generate the discovery report'",
            "type": "integer"
        },
        "reportType": {
            "description": "The report type",
            "type": "string"
        },
        "reportJSON": {
        	"description" : "The discovered object" , 
			"type": "object" ,
			"required": ["certificates"],
            "properties": {
            	"certificates": {
            	"description": "The discovered certificates array" , 
            	"type": "array" ,
            	"items": {
					"type": "object" , 
					"required" : ["certB64" , "certPath" , "hostFQDN" , "appVersion" , "appConfPath" , "appProduct"],
                "properties": {
	            	"certB64": {
	            	  	"type": "string"
	            	},
	            	"certFileExt": {
	            		"type": "string"
	            	},
	            	"certFileName": {
	            		"type": "string"
	            	},
	            	"certPath": {
	            		"type": "string"
	            	},
	            	"privateKeyPath": {
	            		"type": "string"
	            	},
	            	"hostFQDN": {
	            		"type": "string"
	            	},
	            	"appProduct": {
	            		"type": "string"
	            	},
	            	"appVersion": {
	            		"type": "string"
	            	},
	            	"appConfPath": {
	            		"type": "string"
	            	}
            	}
            	
       		  }
     }    

	}
	},
		"startedAt": {
			"description": "Discovery job start data-time",
			"type": "string",
			"format": "date-time"
		},
		"finishedAt": {
			"description": "Discovery job finish data-time",
			"type": "string",
			"format": "date-time"
		}
	}
	
	
}`

- Instance to validate with one violation (agentId required but not exist)
`
{	
        "agentType" ; "testType" ,
	"reportJSON":  {
	"certificates": [
		{"certB64": "testCertB64", 
		"certFileExt": "testCertFileExt" , 
		"certFileName": "testCertFileName" , 
		"certPath": "testCertPath" , 
		"privateKeyPath": "testPrivateKeyPath" , 
		"hostFQDN": "testHostFQDN", 
		"appProduct": "testAppProduct", 
		"appVersion": "testAppVersion", 
		"appConfPath": "testAppConfPath"}
		]} ,
		"startedAt" : "2019-11-13T20:20:39+00:00" ,
		"finishedAt" : "2019-11-13T20:22:39+00:00"
}
-Validate 
`public static List<String> jsonValidator(File JSONSchemaFile, JSONObject JSONToValidate)
			throws FileNotFoundException {
		List<String> listOfViolations = new ArrayList<>();
		log.debug("starting validate json object...");
		try {
			InputStream schemaStream = new FileInputStream(JSONSchemaFile);
			JSONObject jsonSchema = new JSONObject(new JSONTokener(schemaStream));
			Schema schema = SchemaLoader.load(jsonSchema);
			schema.validate(JSONToValidate);
		} catch (ValidationException e) {
			
	listOfViolations = e.getCausingExceptions().stream().map(ValidationException::getMessage)
						.collect(Collectors.toList());
			
		}
		return listOfViolations;
	}`

- Expected behaviour 
listOfViolations : [#: required key [agentId] not found]
-Actual behaviour
listOfViolations : []

**Comment by erosb** [comment] 2019-06-25 07:52
Hi @electronABS I ran a test with your input and got the following output (by calling `Validationexception#toJSON()`, which looks correct for me (2 causing exceptions): 
```json
{
    "causingExceptions": [
        {
            "causingExceptions": [],
            "keyword": "required",
            "message": "required key [agentId] not found",
            "pointerToViolation": "#",
            "schemaLocation": "#"
        },
        {
            "causingExceptions": [],
            "keyword": "required",
            "message": "required key [reportType] not found",
            "pointerToViolation": "#",
            "schemaLocation": "#"
        }
    ],
    "message": "2 schema violations found",
    "pointerToViolation": "#",
    "schemaLocation": "#"
}
```

Reproduction testcase added in 0d797d03bafccb7d6f050ba4bb20758f65d1eafb

**Comment by electronABS** [comment] 2019-06-25 12:53
@erosb 
thanks for your reply ! And how can I user Validationexception#toJSON?
