### ISSUE TITLE
Validation Error using Floats

### ISSUE THREAD

**Issue by BeneSte** [everit-org/json-schema#322] opened 2019-08-20 09:41 UTC
I am writing code that infers a simple JSON schema from an instantiated POJO. 
The schema is used to register objects in a registry, which in turn can be used later to check whether an object that is to be used for other purposes has previously been registered. Simply put, the structure and content should be the same for schema and object. 
E.g. this static class:
```
public static class SimpleTestClass {
    public String stringKey = "issue";
    public float floatKey =  10.1f;
}
```
is serialized to this JSON object.
```
{
  "stringKey": "issue",
  "floatKey": 10.1
}
```
Using my schema generator for this object results in this simple JSON schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "The SimpleTestClass Schema",
  "required": [
    "stringKey",
    "floatKey"
  ],
  "properties": {
    "stringKey": {
      "const": "issue",
      "title": "The stringKey Schema",
      "type": "string"
    },
    "floatKey": {
      "maximum": 10.1,
      "title": "The floatKey Schema",
      "type": "number",
      "minimum": 10.1
    }
  }
}
```
So far so good. 
However, when validating the JSON objects against the schema, the following error occurs which looks wrong to me
```
#/floatKey: 10.1 is not greater or equal to 10.1
```

Using the primitive <tt>double</tt> or casting <tt>float</tt> to <tt>double</tt> works. 
However, using another type except <tt>float</tt> is no solution for the application.
Is this a known issue or are there any solutions for it? 
Thanks in advance!

**Comment by erosb** [comment] 2019-08-28 14:53
Hello,
this should be annoying. Couldn't reproduce it on the library level though (checked in fbfe66ae6e3f3bd829bc86a64947744f543359df ). I think the `10.1` literal in the JSON is parsed into a `double` value, and that causes the problem. It can't really be fixed in this library, since the parsing happens in the org.json library.

You may attempt deep-traversing your in-memory JSONObject and replacing all Double values with their Float rounded approximate. That's hacky and not sure if it will help you.

**Comment by BeneSte** [comment] 2019-09-04 09:34
Thanks for your reply and your work!

**Closed** 2019-09-20 17:07 UTC
