### ISSUE TITLE
Library not supporting num offset in date-time format as per RFC-3339 Section 5.6

### ISSUE THREAD

**Issue by itsgauravjain22** [everit-org/json-schema#81] opened 2017-04-05 07:00 UTC
I got below exception while doing validation check for format "date-time"

[2014-12-29T08:07:44.057+0000] is not a valid date-time. Expected [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,9}Z]

Expected formats should modified accordingly: 
[DateTimeFormatValidator.java](https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/internal/DateTimeFormatValidator.java)

**Comment by erosb** [comment] 2017-04-05 07:18
@itsgauravjain22 which version of the library do you use? Can you reproduce it with `1.5.1` ?

**Comment by itsgauravjain22** [comment] 2017-04-06 06:09
Yes issue is in 1.5.1 version. The above exception is thrown from 1.5.1 version

**Comment by itsgauravjain22** [comment] 2017-04-17 05:45
@erosb Any update regarding the issue.

**Comment by erosb** [comment] 2017-04-18 06:53
@itsgauravjain22 would you please give some example date-time strings which should pass the validation in your usecase? I need a more specific bugreport. Thanks.

**Comment by itsgauravjain22** [comment] 2017-04-24 05:17
**2014-12-29T08:07:44.057+0000** is the date-time sting present in actual response which I want to validate with string format date-time in json schema. But I got the following exception:

_[2014-12-29T08:07:44.057+0000] is not a valid date-time. Expected [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,9}Z]_

I think expected formats should be modified accordingly:
[DateTimeFormatValidator.java](https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/internal/DateTimeFormatValidator.java)

**Comment by erosb** [comment] 2017-04-26 08:29
@itsgauravjain22 section 5.6 of RFC3339 defines the offset as:

`time-numoffset  = ("+" / "-") time-hour ":" time-minute`

Your input doesn't contain the semicolon (":") between between time-hour and time-minute, that is the reason of the failure.

Please let me know if you disagree, otherwise I'll close this ticket.

**Closed** 2017-04-27 15:29 UTC
